### ISSUE TITLE
cobertura coverage sensor allow for lowercase filename

### ISSUE THREAD

**Issue by shader-man** [SonarOpenCommunity/sonar-cxx#1682]
Hi,

generating a  cobertura report from opencppcoverage fill all the "filename" paths in lowercase ( info extracted from PDB files on windows )

`<?xml version="1.0" encoding="utf-8"?>
<coverage line-rate="0.34319526627218933" branch-rate="0" complexity="0" branches-covered="0" branches-valid="0" timestamp="0" lines-covered="116" lines-valid="338" version="0">
  <sources>
    <source>f:</source>
  </sources>
  <packages>
    <package name="f:/build/MyDLL.dll" line-rate="0.34319526627218933" branch-rate="0" complexity="0">
      <classes>
        <class name="file.h" filename="f:/my/file/path/file.h" line-rate="0" branch-rate="0" `complexity="0">`

the cobertura coverage sensor cannot associate the file path in mixed case with this windows lower case path and gives the following error :
 `07:44:03.310 INFO: Added coverage report 'f:/My/File/Path/report.xml' (parsed by: CoberturaParser)
07:44:03.311 DEBUG: save coverage measure for file: 'f:/my/file/path/file.h' cxxFile = 'null'
07:44:03.311 DEBUG: Cannot find the file 'f:/my/file/path/file.h', ignoring coverage measures`

I fed a case-correct cobertura to the plugin and it worked.

would it be possible to ignore the casing for file association?

thanks,

**Comment by guwirth** [comment]
Hi @shader-man,

which version of the plugin are you using? There was a similar issue we fixed with 1.2.2 snapshot (#1678, #1679). You can download it from here: https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts

Regards,

**Comment by shader-man** [comment]
Hi @guwirth ,
i have the version C++ (Community) 1.2.2.1653 installed and running but it stil can't find my files 

`07:44:03.310 INFO: Added coverage report 'f:/My/File/Path/report.xml' (parsed by: CoberturaParser) 
07:44:03.311 DEBUG: save coverage measure for file: 'f:my/file/path/file.h' cxxFile = 'null' 
07:44:03.311 DEBUG: Cannot find the file 'f:my/file/path/file.h', ignoring coverage measures`

I don't know if the problem is still because of the lowercase or because i'm missing a / between my drive letter and the root folder.
in my opencppcoverage generated cobertura xml ,  file i have the following : 
`....
  <sources>
    <source>f:</source>
  </sources>
...
<class name="file.h" filename="my/file/path/file.h" line-rate="0" branch-rate="0" complexity="0">
...
`
should there be a / inserted somewhere ?  in < source > or < filename > ? 
thanks

**Comment by amai2012** [comment]
@shader-man  Did you forget to re-open this issue?

For me plugin 2.0.5 still shows the same problem.
But probably the best fix would be adressing this in https://github.com/OpenCppCoverage/OpenCppCoverage/issues/53
